apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  name: phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    targetPort: 5000
    name: phpmyadmin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: PMA_HOST
            value: mysql
          - name: PMA_PORT
            value: "3306"
          - name: PMA_USER
            value: root
          - name: MYSQL_ROOT_PASSWORD
            value: password