apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - port: 21
    name: ftps
  - port: 20
    name: ftps-20
  - port: 21000
    name: ftps-21000
  - port: 21001
    name: ftps-21001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        env:
          - name: USER
            value: user
          - name: PASSWORD
            value: password
        ports:
          - containerPort: 21
          - containerPort: 20
          - containerPort: 21000
          - containerPort: 21001
